#if !canImport(ObjectiveC)
  import XCTest

  extension PackageListValidatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PackageListValidatorTests = [
      ("testExample", testExample)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(PackageListValidatorTests.__allTests__PackageListValidatorTests)
    ]
  }
#endif
